language: ruby
before_install: gem install bundler
script: ./script/cibuild
after_success: s3_website push
addons:
  apt:
    packages:
      - libcur14-openssl-dev
cache: bundler
notifications:
  email:
    recipients:
      - just4ink007@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: thinkty.net
  skip_cleanup: true
  local_dir: _site