# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
locale           : "en-US" # ko-KR , en-US
title            : "Blog"
description      : ""
baseurl          : "" # the subpath of your site, e.g. /blog
url              : "https://thinkty.net" # the base hostname & protocol for your site
words_per_minute : 200 # for estimating reading time
email            : "the.thinkty@gmail.com"
author           : "Tae Yoon Kim"

# Theme settings
favicon               : "assets/favicons/favicon.ico"
theme                 : no-style-please

# SEO Related do this after you get a domain name
# google_site_verification : Done through DNS record
# bing_site_verification   : 
# yandex_site_verification :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - _archived/
  - README.md
  - LICENSE
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      read_time: true  # add 'read_time: false' to front matter to override

# Archiving
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: /categories/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jemoji
