# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Site settings
theme                 : "minimal-mistakes-jekyll"
minimal_mistakes_skin : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                : "en-US" # ko-KR , en-US
title                 : "Meerkatz"
subtitle              : "Personal blog"
name                  : "Tae Yoon Kim"
description           : >- # this means to ignore newlines until "baseurl:"
  A personal blog to share my thoughts, projects, and hobbies.
baseurl               : "" # the subpath of your site, e.g. /blog
url                   : "https://thinkty.net" # the base hostname & protocol for your site
repository            : "thinkty/homepage-jekyll"
head_scripts          : # add scripts to the <head>
footer_scripts        : # add scripts to the </body>
future                : true
# This image can be overriden at anytime by applying " header: teaser: " to the front matter
# Photo by Richard Bell on Unsplash
#   - /assets/images/meerkat.jpg
# Photo by Clovis WOOD on Unsplash
#   - /assets/images/meerkats.jpg
# Meerkat by parkjisun from the Noun Project
#   - /assets/images/noun_meerkat_icon.png
# Meerkat by ArmOkay from the Noun Project
#   - /assets/images/noun_meerkat_cute_logo.png
# Photo by Amanda Swanepoel on Unsplash
#   - /assets/images/meerkat_bw.png
# teaser                : "/assets/images/meerkat.jpg"
logo                  : "/assets/images/noun_meerkat_cute_logo.png"
words_per_minute      : 200 # for estimating reading time
email                 : "just4ink007@gmail.com"
github_username       : "thinkty"
search                : true
search_full_content   : true
search_provider       : "algolia" # default is lunr
algolia:
  application_id      : "4UJ1WD4AIU"
  index_name          : "meerkatz"
  search_only_api_key : "64845f9080f01e8f53cba4cc457fca1c"
  powered_by          : false

# SEO Related TODO: do this after you get a domain name
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :

# Social Sharing
social:
  type                : "Person"
  name                : "Tae Yoon Kim"
  links:
    - "https://www.linkedin.com/in/thinkty/"
    - "https://github.com/thinkty"

# Analytics TODO:
# analytics:
#   provider               : false # false (default), "google", "google-universal", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "Tae Yoon Kim"
  # avatar           : "assets/images/noun_meerkat_icon.png"
  bio              : "Student & Programmer"
  location         : "Indiana & Seoul"
  email            : "just4ink007@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:just4ink007@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thinkty"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thinkty"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - deploy.sh
  - netlify.toml
  - Dockerfile
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      read_time: true  # add read_time: false to front matter to override
      comments: false
      author_profile: false
      share: true
      related: true
  - scope:
      path: ""
      type: tag
    values:
      comments: false
  - scope:
      path: ""
      type: category
    values:
      comments: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives
  - jemoji

# Archiving
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
